// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFXSS2-nRlZE1lfPLFdqZVgXMMsuPM6Do',
    appId: '1:840373323269:android:ea7d5f8b06a6ad6d40fe6c',
    messagingSenderId: '840373323269',
    projectId: 'pnustudenthousing-5f74c',
    databaseURL: 'https://pnustudenthousing-5f74c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pnustudenthousing-5f74c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThD01sXxlrmOjUlpMgKKjX8BEsPnrAeE',
    appId: '1:840373323269:ios:88deb94d6eb6721140fe6c',
    messagingSenderId: '840373323269',
    projectId: 'pnustudenthousing-5f74c',
    databaseURL: 'https://pnustudenthousing-5f74c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pnustudenthousing-5f74c.appspot.com',
    iosBundleId: 'com.example.pnuHousing',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1EbMym1Z5h1RAM-3dyDt0wF12fMMyIs',
    appId: '1:840373323269:web:c1c491167afbe2b340fe6c',
    messagingSenderId: '840373323269',
    projectId: 'pnustudenthousing-5f74c',
    authDomain: 'pnustudenthousing-5f74c.firebaseapp.com',
    databaseURL: 'https://pnustudenthousing-5f74c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pnustudenthousing-5f74c.appspot.com',
    measurementId: 'G-8XDDBVQ3JG',
  );

}